**ONLY FOR BOYS**

CHANCE TO HAVE THREESOM WITH HOT CHEEKS CALCULATOR v.1

This product is not a guide to action.
Use it at your own risk

Thousands of people around the world have already tested this product. Among them are well-known [politicians](https://www.facebook.com/Johnny.Sins.Official/), [doctors](https://www.facebook.com/Johnny.Sins.Official/), [cosmonauts](https://www.facebook.com/Johnny.Sins.Official/) and many others.
This product guarantees a 100% chance to determine the probability of jackpot.
Don't fuck with NN.

ALL RIGHTS RESERVED

In [1]:
import numpy as np
from scipy import optimize
import matplotlib.pyplot as plt
from random import choice
from scipy.special import expit
%matplotlib inline

To calculate your chanse, run the code below.

In [2]:
jonhson_size = np.array(([5],[10],[15],[20],
                         [25],[17],[24], [3]), dtype=float)

salary = np.array(([100],[500],[1000],[5000],
                   [20000],[40000],[1000000],[1000000]), dtype=float)

chance_to_have_threesom_with_hot_cheeks = np.array(([0.5],[10],[20],[55],
                                                    [74],[65], [99], [97.5]), 
                                                   dtype=float)

jonhson_size_n = jonhson_size/np.amax(jonhson_size, axis=0)

salary_n = salary /np.amax(salary, axis=0)

X = np.hstack((jonhson_size_n,salary_n))

y = chance_to_have_threesom_with_hot_cheeks/100

In [3]:
class Neural_Network(object):
    def __init__(self):        
        #Define Hyperparameters
        self.inputLayerSize = 2
        self.outputLayerSize = 1
        self.hiddenLayerSize = 6
        
        #Weights (parameters)
        self.W1 = np.random.randn(self.inputLayerSize,self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize,self.outputLayerSize)
        
    def forward(self, X):
        #Propogate inputs though network
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3) 
        return yHat
        
    def sigmoid(self, z):
        #Apply sigmoid activation function to scalar, vector, or matrix
        return 1/(1+np.exp(-z))
    
    def sigmoidPrime(self,z):
        #Gradient of sigmoid
        return np.exp(-z)/((1+np.exp(-z))**2)
    
    def costFunction(self, X, y):
        #Compute cost for given X,y, use weights already stored in class.
        self.yHat = self.forward(X)
        J = 0.5*sum((y-self.yHat)**2)
        return J
        
    def costFunctionPrime(self, X, y):
        #Compute derivative with respect to W and W2 for a given X and y:
        self.yHat = self.forward(X)
        
        delta3 = np.multiply(-(y-self.yHat), self.sigmoidPrime(self.z3))
        dJdW2 = np.dot(self.a2.T, delta3)
        
        delta2 = np.dot(delta3, self.W2.T)*self.sigmoidPrime(self.z2)
        dJdW1 = np.dot(X.T, delta2)  
        
        return dJdW1, dJdW2
    
    #Helper Functions for interacting with other classes:
    def getParams(self):
        #Get W1 and W2 unrolled into vector:
        params = np.concatenate((self.W1.ravel(), self.W2.ravel()))
        return params
    
    def setParams(self, params):
        #Set W1 and W2 using single paramater vector.
        W1_start = 0
        W1_end = self.hiddenLayerSize * self.inputLayerSize
        self.W1 = np.reshape(params[W1_start:W1_end], (self.inputLayerSize , self.hiddenLayerSize))
        W2_end = W1_end + self.hiddenLayerSize*self.outputLayerSize
        self.W2 = np.reshape(params[W1_end:W2_end], (self.hiddenLayerSize, self.outputLayerSize))
        
    def computeGradients(self, X, y):
        dJdW1, dJdW2 = self.costFunctionPrime(X, y)
        return np.concatenate((dJdW1.ravel(), dJdW2.ravel()))

In [4]:
class trainer(object):
    def __init__(self, N):
        #Make Local reference to network:
        self.N = N
        
    def callbackF(self, params):
        self.N.setParams(params)
        self.J.append(self.N.costFunction(self.X, self.y))   
        
    def costFunctionWrapper(self, params, X, y):
        self.N.setParams(params)
        cost = self.N.costFunction(X, y)
        grad = self.N.computeGradients(X,y)
        
        return cost, grad
        
    def train(self, X, y):
        #Make an internal variable for the callback function:
        self.X = X
        self.y = y

        #Make empty list to store costs:
        self.J = []
        
        params0 = self.N.getParams()

        options = {'maxiter': 200, 'disp' : True}
        _res = optimize.minimize(self.costFunctionWrapper, params0, jac=True, method='BFGS', \
                                 args=(X, y), options=options, callback=self.callbackF)

        self.N.setParams(_res.x)
        self.optimizationResults = _res

In [5]:
NN = Neural_Network()

In [6]:
T = trainer(NN)

In [7]:
T.train(X,y)

         Current function value: 0.001827
         Iterations: 200
         Function evaluations: 223
         Gradient evaluations: 223


In [8]:
NN.costFunctionPrime(X,y)

(array([[ -2.67750258e-04,  -2.40372854e-04,  -3.06881326e-05,
           3.17022123e-06,  -7.37060008e-05,   1.01773368e-03],
        [ -1.76417042e-05,  -4.11326943e-06,   1.97812344e-07,
           1.10689423e-07,  -1.79251898e-06,   3.95434311e-05]]),
 array([[  3.28952684e-05],
        [  1.92702000e-05],
        [  2.09394052e-04],
        [ -1.13023902e-05],
        [  2.02785219e-05],
        [  8.34174965e-05]]))

In [9]:
NN.forward(X) * 100

array([[  1.97036434],
       [  6.24429889],
       [ 23.01396125],
       [ 52.93793338],
       [ 74.98119098],
       [ 65.0368199 ],
       [ 98.75594885],
       [ 99.9313303 ]])

In [10]:
y

array([[ 0.005],
       [ 0.1  ],
       [ 0.2  ],
       [ 0.55 ],
       [ 0.74 ],
       [ 0.65 ],
       [ 0.99 ],
       [ 0.975]])

In [11]:
def calculate_your_chance(size, sal,ar1 = jonhson_size, ar2 = salary):
    if size > 30:
        print('( ͡° ͜ʖ ͡°) ' + ' OH BOI')
    ar1 = np.append(ar1, np.array([size]))
    ar1 = ar1/np.amax(ar1, axis=0)
    ar2 = np.append(ar2, np.array([sal]))
    ar2 = ar2/np.amax(ar2, axis=0)
    X1 = np.hstack((ar1.reshape((ar1.size, 1)),
                    ar2.reshape((ar2.size, 1))))
    return  X1

Input ur johnson's size in cm and ur monthly salary in $

In [13]:
size = float((input('Input ur boi  ')))
sal = float((input('Input ur salary  ')))

print('Your chance to have fun is ' + \
      str(NN.forward(calculate_your_chance(size, sal)).item(-1) * 100) + '%')

Input ur boi  20
Input ur salary  1000
Your chance to have fun is 49.837598571940624%


I'm not a sexist. Sorry girls, I promise I'll make some kind of calculator for you in next version.

This calculator is for lulz. If you don't like it, go fuck yourself.